apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transit-lakehouse.fullname" . }}
  labels: {{- include "transit-lakehouse.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
