{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: transit-lakehouse-api
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    {{- if .Values.networkPolicy.egress.allowDns }}
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- end }}
    {{- range .Values.networkPolicy.egress.allowToCidrs }}
    - to:
        - ipBlock:
            cidr: {{ . }}
    {{- end }}
{{- end }}

# end of network policy
