{{- if and .Values.autoscaling.enabled .Values.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "transit-lakehouse.fullname" . }}
  labels: {{- include "transit-lakehouse.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "transit-lakehouse.fullname" . }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  triggers:
    {{- toYaml .Values.keda.triggers | nindent 4 }}
{{- end }}
