{{- if .Values.secrets.csi.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "transit-lakehouse.fullname" . }}
  labels: {{- include "transit-lakehouse.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.secrets.csi.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.secrets.csi.keyVaultName | quote }}
    tenantId: {{ .Values.secrets.csi.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secrets.csi.objects }}
        - |
          objectName: {{ .name }}
          objectType: {{ .type | default "secret" }}
        {{- end }}
  secretObjects:
    - secretName: {{ include "transit-lakehouse.fullname" . }}-csi
      type: Opaque
      data:
        {{- range .Values.secrets.csi.objects }}
        - objectName: {{ .name }}
          key: {{ .envKey | default .name }}
        {{- end }}
{{- end }}
